/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
    id("io.freefair.lombok") version "8.10.2"
    `maven-publish`
}

dependencies {
    implementation(project(":common"))
    implementation(platform(libs.sdk.bom))
    implementation(libs.s3);
    implementation(libs.crt);

    testImplementation(libs.junit.jupiter)
    testImplementation(libs.mockito.core)
    testImplementation(libs.mockito.junit.jupiter)
    testRuntimeOnly(libs.junit.jupiter.launcher)
}

tasks.test {
    environment("AWS_REGION", "eu-west-1")
}

publishing {
    publications {
        create<MavenPublication>("objectClient") {
            groupId = "com.amazon.connector.s3"
            version = "0.0.1"

            from(components["java"])
        }
    }
}
