/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {

    testImplementation(libs.junit.jupiter)
    testImplementation(libs.mockito.core)
    testImplementation(libs.mockito.junit.jupiter)
    testRuntimeOnly(libs.junit.jupiter.launcher)
    implementation(platform("software.amazon.awssdk:bom:2.25.31"))
    implementation("software.amazon.awssdk:s3")
    implementation("software.amazon.awssdk.crt:aws-crt:0.29.10")
}
