name: Build and upload artifact JARs to S3 treatment bucket

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches:
      - main
      - cicd-builds

env:
  AWS_REGION :  ${{ vars.AWS_REGION }} # Change to reflect your region
  S3_BUCKET : ${{ vars.S3_BUCKET }}
  STATE_MACHINE_ARN : ${{ secrets.STATE_MACHINE_ARN }}
  ROLE_TO_ASSUME: ${{ secrets.ASSUME_ROLE_ARN }}
  STATE_MACHINE_INPUT_S3A: ${{ vars.STATE_MACHINE_INPUT_S3A }}
  STATE_MACHINE_INPUT_S3FILEIO: ${{ vars.STATE_MACHINE_INPUT_S3FILEIO }}

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  BuildAnalyticsAcceleratorAndUploadArtifact:
    name: Build library artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle
        run: |
          ./gradlew -PsnapshotBuild=true build
          ./gradlew jmhJar

      - uses: actions/upload-artifact@v4
        with:
          path: "input-stream/build/libs/analyticsaccelerator-s3-SNAPSHOT.jar"
          name: "analyticsaccelerator-s3-SNAPSHOT.jar"

  BuildIcebergAndUploadArtifact:
    name: Build Iceberg artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build and publish to local Maven with Gradle
        run: |
          ./gradlew -PsnapshotBuild=true publishToMavenLocal 

      - name: Setup Iceberg SSH deploy key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ICEBERG_STAGING_SSH_KEY }}

      - name: Checkout Iceberg
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.ICEBERG_STAGING_PATH }}
          ref: analytics-accelerator
          path: iceberg
          ssh-key: ${{ secrets.ICEBERG_STAGING_SSH_KEY }}

      - name: Build Iceberg jar
        run: |
          ./gradlew build-DsparkVersions=3.5
        working-directory: iceberg
