name: build iceberg tests

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  workflow_dispatch:

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  BuildAnalyticsAcceleratorAndUploadArtifact:
    name: Build library artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle
        run: |
          ./gradlew -PsnapshotBuild=true build

      - uses: actions/upload-artifact@v4
        with:
          path: "input-stream/build/libs/analyticsaccelerator-s3-SNAPSHOT.jar"
          name: "analyticsaccelerator-s3-SNAPSHOT.jar"

  BuildIcebergAndUploadArtifact:
    needs: BuildAnalyticsAcceleratorAndUploadArtifact
    name: Build Iceberg artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build and publish to local Maven with Gradle
        run: |
          ./gradlew -PsnapshotBuild=true publishToMavenLocal 

      - name: Checkout Iceberg
        uses: actions/checkout@v4
        with:
          repository: apache/iceberg
          ref: main
          path: iceberg

      - name: Build Iceberg jar
        run: |
          ./gradlew build -x test -x integrationTest -DsparkVersions=3.5
        working-directory: iceberg

